# Generated by Django 2.0.7 on 2018-07-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_query_result_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='lang',
            field=models.CharField(blank=True, default='pt', max_length=200, null=True),
        ),
    ]
