# Generated by Django 2.0.7 on 2018-07-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_query_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='geocode',
            field=models.CharField(blank=True, help_text='latitude longitude radius(mi or km)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='locale',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='max_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='since_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='until',
            field=models.CharField(blank=True, help_text='YYYY-MM-DD', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='result_type',
            field=models.CharField(choices=[('popular', 'Popular'), ('recent', 'Recent'), ('mixed', 'Mixed')], default='recent', max_length=200, verbose_name='result_type'),
        ),
    ]
