# Generated by Django 2.0.7 on 2018-07-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180717_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='most_common_stem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='most_common_word',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
