# Generated by Django 2.0.7 on 2018-07-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_verified'),
        ('core', '0005_auto_20180717_1706'),
    ]

    operations = [
    ]
