# Generated by Django 2.0.7 on 2018-08-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20180724_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='tweets',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='core.Tweet'),
        ),
    ]
