# Generated by Django 2.0.7 on 2018-08-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180807_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
