# Generated by Django 2.1 on 2018-08-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180816_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='display_url',
            field=models.CharField(max_length=100),
        ),
    ]
