# Generated by Django 2.1 on 2018-08-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180817_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='expanded_url',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
