# Generated by Django 2.1 on 2018-08-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180817_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='most_common_stem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='most_common_word',
            field=models.TextField(blank=True, null=True),
        ),
    ]
