# Generated by Django 2.1 on 2018-08-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='description',
        ),
        migrations.RemoveField(
            model_name='link',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='link',
            name='site_name',
        ),
    ]
