# Generated by Django 2.1 on 2018-08-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='most_common_stem',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='most_common_word',
        ),
    ]
