# Generated by Django 2.1 on 2018-09-13 13:51

from django.db import migrations, models
import django.db.models.deletion


def migrate_m2m_data(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    TweetCategory = apps.get_model("core", "TweetCategory")

    for category in Category.objects.all():
        for tweet in category.tweets.all():
            TweetCategory.objects.create(tweet=tweet, category=category, is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180823_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'tweet category',
                'verbose_name_plural': 'tweets categories',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='sql',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweetcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
        migrations.AddField(
            model_name='tweetcategory',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tweet'),
        ),
        migrations.RunPython(
            migrate_m2m_data
        ),
        migrations.RemoveField(
            model_name='category',
            name='tweets',
        ),
        migrations.AddField(
            model_name='category',
            name='tweets',
            field=models.ManyToManyField(blank=True, related_name='categories', through='core.TweetCategory', to='core.Tweet'),
        ),
    ]
