# Generated by Django 2.1.1 on 2018-09-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180919_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'profile type',
                'verbose_name_plural': 'profile types',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('default', 'Default'), ('congressman', 'Congressman'), ('press', 'Press')], default='default', max_length=200, verbose_name='profile type'),
        ),
    ]
