# Generated by Django 2.1.1 on 2018-09-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180921_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='tweets',
            field=models.ManyToManyField(blank=True, null=True, to='core.Tweet'),
        ),
    ]
