# Generated by Django 2.1.1 on 2018-09-25 18:43

from django.db import migrations, models


def migrate_data(apps, schema_editor):
    Category = apps.get_model("core", "Category")

    for category in Category.objects.all():
        query = category.queries.first()
        tweets = category.tweets.values_list('id', flat=True)
        query.tweets.add(*tweets)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180926_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='tweets',
            field=models.ManyToManyField(related_name='queries', to='core.Tweet'),
        ),
        migrations.RunPython(
            migrate_data
        ),
    ]
