# Generated by Django 2.1.1 on 2018-10-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_query_tweets'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql', models.TextField(verbose_name='text')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'sql filter',
                'verbose_name_plural': 'sql filters',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='sql',
            field=models.TextField(blank=True, help_text="SELECT * FROM 'core_tweet' WHERE 'core_tweetcategory'.'category_id' = < category_id > AND ...", null=True),
        ),
    ]
